apiVersion: v1
data:
  discourse-password: NFZnWEh3eXN4bQ==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: discourse
    helm.sh/chart: discourse-5.2.3
  name: RELEASE-NAME-discourse-discourse
type: Opaque
