apiVersion: v1
data:
  mysql-password: b285NnYxR0J6Zg==
  mysql-root-password: QzVsVEdFYlhzSA==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-8.8.23
  name: RELEASE-NAME-mysql
  namespace: default
type: Opaque
