apiVersion: v1
data:
  dokuwiki-password: R2k3Vm9WNTNYdg==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dokuwiki
    helm.sh/chart: dokuwiki-12.2.1
  name: RELEASE-NAME-dokuwiki
type: Opaque
