apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 20.0.1
    chart: kube-prometheus-stack-20.0.1
    heritage: Helm
    release: RELEASE-NAME
  name: RELEASE-NAME-kube-promethe-prometheus-psp
rules:
- apiGroups:
  - policy
  resourceNames:
  - RELEASE-NAME-kube-promethe-prometheus
  resources:
  - podsecuritypolicies
  verbs:
  - use
