apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cass-operator
    app.kubernetes.io/part-of: k8ssandra-RELEASE-NAME-default
    helm.sh/chart: cass-operator-0.32.0
  name: RELEASE-NAME-cass-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: RELEASE-NAME
      app.kubernetes.io/name: cass-operator
      app.kubernetes.io/part-of: k8ssandra-RELEASE-NAME-default
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: cass-operator
        app.kubernetes.io/part-of: k8ssandra-RELEASE-NAME-default
        helm.sh/chart: cass-operator-0.32.0
    spec:
      containers:
      - args:
        - --config=/configs/controller_manager_config.yaml
        command:
        - /manager
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: docker.io/k8ssandra/cass-operator:v1.9.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: cass-operator
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {}
        securityContext:
          readOnlyRootFilesystem: true
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
        volumeMounts:
        - mountPath: /configs
          name: manager-config
      securityContext: {}
      serviceAccountName: RELEASE-NAME-cass-operator
      volumes:
      - configMap:
          name: RELEASE-NAME-cass-operator-manager-config
        name: manager-config
