apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 20.0.1
    chart: kube-prometheus-stack-20.0.1
    heritage: Helm
    release: RELEASE-NAME
  name: RELEASE-NAME-kube-promethe-prometheus
  namespace: default
spec:
  alerting:
    alertmanagers: []
  enableAdminAPI: false
  externalUrl: http://RELEASE-NAME-kube-promethe-prometheus.default:9090
  image: quay.io/prometheus/prometheus:v2.28.1
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: RELEASE-NAME
  portName: web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: RELEASE-NAME
  replicas: 1
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      app: kube-prometheus-stack
      release: RELEASE-NAME
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: RELEASE-NAME-kube-promethe-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: RELEASE-NAME
  shards: 1
  version: v2.28.1
