apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.5.11
    helm.sh/chart: grafana-6.17.5
  name: RELEASE-NAME-grafana-test
  namespace: default
rules:
- apiGroups:
  - policy
  resourceNames:
  - RELEASE-NAME-grafana-test
  resources:
  - podsecuritypolicies
  verbs:
  - use
