apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.5.11
    helm.sh/chart: grafana-6.17.5
  name: RELEASE-NAME-grafana
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: RELEASE-NAME-grafana
subjects:
- kind: ServiceAccount
  name: RELEASE-NAME-grafana
  namespace: default
