apiVersion: v1
data:
  tls.crt: ""
  tls.key: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cass-operator
    app.kubernetes.io/part-of: k8ssandra-RELEASE-NAME-default
    helm.sh/chart: cass-operator-0.32.0
  name: RELEASE-NAME-webhook
