apiVersion: v1
data:
  admin-password: c2VjcmV0
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.5.11
    helm.sh/chart: grafana-6.17.5
  name: RELEASE-NAME-grafana
  namespace: default
type: Opaque
