apiVersion: v1
data:
  password: eVBBR1psRkFxelJmQ2l3TkpENDE=
  username: UkVMRUFTRS1OQU1FLXN1cGVydXNlcg==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8ssandra
    app.kubernetes.io/part-of: k8ssandra-RELEASE-NAME-default
    helm.sh/chart: k8ssandra-1.4.1
  name: RELEASE-NAME-superuser
type: Opaque
