apiVersion: v1
data:
  rcon-password: Q0hBTkdFTUUh
kind: Secret
metadata:
  labels:
    app: RELEASE-NAME-minecraft
    chart: minecraft-3.7.2
    heritage: Helm
    release: RELEASE-NAME
  name: RELEASE-NAME-minecraft
type: Opaque
