- name: alertmanager
  repo: https://prometheus-community.github.io/helm-charts
- name: apertium
  repo: https://helm-charts.wikimedia.org/stable/
- name: argo-cd
  repo: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  type: raw
- name: athenz-zms
  repo: https://raw.githubusercontent.com/AthenZ/athenz/master/kubernetes/charts
- name: athenz-zts
  repo: https://raw.githubusercontent.com/AthenZ/athenz/master/kubernetes/charts
- name: cassandra
  repo: https://charts.bitnami.com/bitnami
- name: cert-manager
  repo: https://charts.jetstack.io
- name: chartmuseum
  repo: https://chartmuseum.github.io/charts
- name: cockroachdb
  repo: https://charts.cockroachdb.com/
- name: concourse
  repo: https://concourse-charts.storage.googleapis.com/
- name: consul
  repo: https://helm.releases.hashicorp.com
- name: contour
  repo: https://charts.bitnami.com/bitnami
- name: coredns
  repo: https://coredns.github.io/helm
- name: crossplane
  repo: https://charts.crossplane.io/stable
- name: dask
  repo: https://helm.dask.org/
- name: datadog
  repo: https://helm.datadoghq.com
- name: dex
  repo: https://charts.dexidp.io
- name: discourse
  repo: https://charts.bitnami.com/bitnami
- name: dokuwiki
  repo: https://charts.bitnami.com/bitnami
- name: drone
  repo: https://charts.drone.io
  valuesInline:
    env:
      DRONE_SERVER_HOST: drone.example.com
- name: drupal
  repo: https://charts.bitnami.com/bitnami
- name: elasticsearch
  repo: https://helm.elastic.co
- name: eventrouter
  repo: https://helm-charts.wikimedia.org/stable/
- name: external-dns
  repo: https://kubernetes-sigs.github.io/external-dns/
- name: falco
  repo: https://falcosecurity.github.io/charts
- name: factorio-server-charts
  repo: https://sqljames.github.io/factorio-server-charts/
- name: filebeat
  repo: https://helm.elastic.co
- name: fluent-bit
  repo: https://fluent.github.io/helm-charts
- name: fluentd
  repo: https://fluent.github.io/helm-charts
- name: gitlab
  repo: https://charts.gitlab.io/
  valuesInline:
    certmanager-issuer:
      email: me@example.com
- name: grafana
  repo: https://grafana.github.io/helm-charts
- name: graylog
  repo: https://charts.kong-z.com
- name: harbor
  repo: https://helm.goharbor.io
- name: hazelcast
  repo: https://hazelcast-charts.s3.amazonaws.com/
- name: influxdb
  repo: https://charts.bitnami.com/bitnami
- name: ingress-nginx
  repo: https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/baremetal/deploy.yaml
  type: raw
- name: istio-base
  chartName: base
  repo: https://istio-release.storage.googleapis.com/charts
- name: istio-gateway
  chartName: gateway
  repo: https://istio-release.storage.googleapis.com/charts
- name: istiod
  repo: https://istio-release.storage.googleapis.com/charts
- name: jenkins
  repo: https://charts.jenkins.io
- name: jfrog-platform
  repo: https://charts.jfrog.io
- name: jmeter-service
  repo: https://charts.keptn.sh
- name: joomla
  repo: https://charts.bitnami.com/bitnami
- name: jupyterhub
  repo: https://jupyterhub.github.io/helm-chart/
- name: k8ssandra
  repo: https://helm.k8ssandra.io/stable
- name: kafka
  repo: https://charts.bitnami.com/bitnami
- name: kask
  repo: https://helm-charts.wikimedia.org/stable/
- name: keycloak
  repo: https://charts.bitnami.com/bitnami
- name: kibana
  repo: https://helm.elastic.co
- name: knative
  repo: https://charts.gitlab.io/
- name: kong
  repo: https://charts.bitnami.com/bitnami
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
- name: kube-state-metrics
  repo: https://prometheus-community.github.io/helm-charts
- name: kubernetes-dashboard
  repo: https://kubernetes.github.io/dashboard/
- name: logstash
  repo: https://helm.elastic.co
- name: loki
  repo: https://grafana.github.io/helm-charts
- name: magento
  repo: https://charts.bitnami.com/bitnami
- name: mariadb
  repo: https://charts.bitnami.com/bitnami
- name: mariadb-galera
  repo: https://charts.bitnami.com/bitnami
- name: mathoid
  repo: https://helm-charts.wikimedia.org/stable/
- name: mattermost-team-edition
  repo: https://helm.mattermost.com
- name: mediawiki
  repo: https://charts.bitnami.com/bitnami
- name: memcached
  repo: https://charts.bitnami.com/bitnami
- name: metallb
  repo: https://metallb.github.io/metallb
- name: metricbeat
  repo: https://helm.elastic.co
- name: metrics-server
  repo: https://kubernetes-sigs.github.io/metrics-server/
- name: minecraft
  repo: https://itzg.github.io/minecraft-server-charts/
  includeCRDs: false
  valuesInline:
    minecraftServer:
      eula: true
      difficulty: hard
      rcon:
        enabled: true
  releaseName: moria
  version: 3.1.3
- name: minio
  repo: https://charts.min.io/
- name: mongodb
  repo: https://charts.bitnami.com/bitnami
- name: moodle
  repo: https://charts.bitnami.com/bitnami
- name: mysql
  repo: https://charts.bitnami.com/bitnami
- name: nats
  repo: https://nats-io.github.io/k8s/helm/charts/
- name: nginx
  repo: https://charts.bitnami.com/bitnami
- name: node-problem-detector
  repo: https://charts.deliveryhero.io/
- name: nuclio
  repo: https://nuclio.github.io/nuclio/charts
- name: oauth2-proxy
  repo: https://oauth2-proxy.github.io/manifests
- name: odoo
  repo: https://charts.bitnami.com/bitnami
- name: opensearch
  repo: https://opensearch-project.github.io/helm-charts/
- name: opensearch-dashboards
  repo: https://opensearch-project.github.io/helm-charts/
- name: parsoid
  repo: https://helm-charts.wikimedia.org/stable/
- name: phpbb
  repo: https://charts.bitnami.com/bitnami
- name: phpmyadmin
  repo: https://charts.bitnami.com/bitnami
- name: postgresql
  repo: https://charts.bitnami.com/bitnami
- name: prestashop
  repo: https://charts.bitnami.com/bitnami
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
- name: prometheus-node-exporter
  repo: https://prometheus-community.github.io/helm-charts
- name: promtail
  repo: https://grafana.github.io/helm-charts
- name: rabbitmq
  repo: https://charts.bitnami.com/bitnami
- name: redis
  repo: https://charts.bitnami.com/bitnami
- name: reloader
  repo: https://stakater.github.io/stakater-charts
- name: redmine
  repo: https://charts.bitnami.com/bitnami
- name: selenium-grid
  repo: https://raw.githubusercontent.com/SeleniumHQ/docker-selenium/trunk/k8s-deployment-full-grid.yaml
  type: raw
- name: solr
  repo: https://solr.apache.org/charts
- name: spark
  repo: https://charts.bitnami.com/bitnami
- name: thanos
  repo: https://charts.bitnami.com/bitnami
- name: tomcat
  repo: https://charts.bitnami.com/bitnami
- name: traefik
  repo: https://helm.traefik.io/traefik
- name: vault
  repo: https://helm.releases.hashicorp.com
- name: velero
  repo: https://vmware-tanzu.github.io/helm-charts/
- name: voyager
  repo: https://charts.appscode.com/stable/
- name: wildfly
  repo: https://docs.wildfly.org/wildfly-charts/
  valuesInline:
    build:
      uri: https://github.com/wildfly/quickstart.git
- name: wordpress
  repo: https://charts.bitnami.com/bitnami
- name: xray
  repo: https://charts.jfrog.io
  valuesInline:
    xray:
      jfrogUrl: "JFROG-URL"
