apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test-success
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 1.8.12
    helm.sh/chart: fluent-bit-0.19.18
  name: RELEASE-NAME-fluent-bit-test-connection
spec:
  containers:
  - args:
    - RELEASE-NAME-fluent-bit:2020
    command:
    - wget
    image: busybox:latest
    imagePullPolicy: Always
    name: wget
  restartPolicy: Never
