apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 1.9.3
    helm.sh/chart: fluent-bit-0.20.0
  name: RELEASE-NAME-fluent-bit
spec:
  ports:
  - name: http
    port: 2020
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/name: fluent-bit
  type: ClusterIP
