apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app: prometheus
    chart: prometheus-15.1.1
    component: server
    heritage: Helm
    release: RELEASE-NAME
  name: RELEASE-NAME-prometheus-server
  namespace: default
